### PR TITLE
Exercise 31 in Java language added

### PR DESCRIPTION
**Pull request by danmoren**
Commit part of Hacktoberfest 2019

### CODE REVIEW

**Comment by AdarshRise** [comment]
Put problem number in file as well.

**Comment by danmoren** [comment]
> Put problem number in file as well.

Done

**Comment by AdarshRise** [comment]
Readme edit?

**Comment by danmoren** [comment]
> Readme edit?

Updated :)

**Comment by AdarshRise** [comment]
Your Readme is not showing in PR.{ As a Pull }

**Comment by danmoren** [comment]
> Your Readme is not showing in PR.{ As a Pull }

Updated in PR https://github.com/RisingLight/Project-Euler/pull/118

**Comment by AdarshRise** [comment]
" //Euler 31 " just add this as well please{ in file }. =)

**Comment by danmoren** [comment]
> " //Euler 31 " just add this as well please{ in file }. =)

Fixed :)

**Comment by AdarshRise** [comment]
Done.

**Pull request merged**
