### PR TITLE
05 done in C

### PR DESCRIPTION
**Pull request by rodneyosodo**
Euler 05 done in C

### CODE REVIEW

**Comment by rodneyosodo** [comment]
@AdarshRise

**Comment by AdarshRise** [comment]
Put problem statement in the file as well.

**Comment by rodneyosodo** [comment]
@AdarshRise I have done it

**Comment by AdarshRise** [comment]
Taking too long. { didn't show any output}

**Comment by AdarshRise** [comment]
I patiently ran it for a while, and got the output. I would like you to optimize it, as the Result is correct I am removing the Bug tag.

**Comment by rodneyosodo** [comment]
Closing  this one @AdarshRise

**Pull request closed without merging**
