### PR TITLE
Problem 12 done in Python

### PR DESCRIPTION
**Pull request by aravp-mobile**

### CODE REVIEW

**Comment by AdarshRise** [comment]
Are you trying to send a collective PR?{ More than one file}

**Comment by aravp-mobile** [comment]
Yes. sending from multiple branch

**Comment by AdarshRise** [comment]
Your PR should mention all incoming files, according to the guideline format, Each file should have the problem Number within it.

**Comment by aravp-mobile** [comment]
I have mentioned the Problem number in the file , its problem no. 12.

**Comment by AdarshRise** [comment]
This PR is sending solutions for 16, 12 ,35. The file{ solution } for 12 has wrong problem within it { it says it's of 11 }, and You Didn't edit the readme as well.

**Pull request closed without merging**
