### PR TITLE
12 done in Py3

### PR DESCRIPTION
**Pull request by ankitrai96**
### Highly Divisible Triangular Number

Please note that the problem statement has been solved using a **naive approach** which is not efficient.

### CODE REVIEW

**Comment by AdarshRise** [comment]
Taking too long, optimize code.

**Comment by ankitrai96** [comment]
@AdarshRise I've optimized the code. It runs significantly faster now.

**Comment by AdarshRise** [comment]
Readme Edit.

**Comment by AdarshRise** [comment]
Put problem number as well, Use this format if you have to " problem_num. Problem_stat", merging now, fix this in another pr later.

**Pull request merged**
