### PR TITLE
solution for Q3 and Q4

### PR DESCRIPTION
**Pull request by Prhmma**

### CODE REVIEW

**Comment by Prhmma** [comment]
solution for Q3 and Q4

**Comment by Prhmma** [comment]
solution added for Q5 and Q6

**Comment by AdarshRise** [comment]
Pr should have proper naming. See the guidelines. and put problem no. in files, do readme edit as well.

**Comment by Prhmma** [comment]
thanks for noticing this, names changed properly

**Comment by AdarshRise** [comment]
Well, it should be like this.
C#/problemNo.problemName(aFolder)/yourname.cs
In "yourname.cs"
Put problem no. As commmet.
And edit the readme( after a git pull) according to the problems done.

You may refer to other already merged PR's

**Pull request closed without merging**
