### PR TITLE
Problem 13 in python

### PR DESCRIPTION
**Pull request by ramonssarmento**

### CODE REVIEW

**Comment by imabhishekkumar** [comment]
Hey, thank you for your contribution! Please check the new contribution guideline and modify your PR accordingly. Thanks!

**Comment by ramonssarmento** [comment]
> 
> 
> Hey, thank you for your contribution! Please check the new contribution guideline and modify your PR accordingly. Thanks!

Done ;)

**Comment by AdarshRise** [comment]
All correct, Resolve the conflict{ do git pull}, and Please do the necessary modification to the file. { just add problem statement }

**Comment by ramonssarmento** [comment]
Sorry for the delay was a little busy

**Comment by AdarshRise** [comment]
done.

**Pull request merged**
