### PR TITLE
Add 01 Multiples of 3 and 5 solution for Swift

### PR DESCRIPTION
**Pull request by NicolasCombe5555**

### CODE REVIEW

**Comment by AdarshRise** [comment]
Problem no. in file. and Resolve Conflict.

**Comment by NicolasCombe5555** [comment]
@AdarshRise done

**Comment by AdarshRise** [comment]
Problem number in file,. As a comment

**Comment by NicolasCombe5555** [comment]
@AdarshRise i added the comment on the file

**Comment by AdarshRise** [comment]
Great.

**Pull request merged**
