### PR TITLE
Solution to 20th project euler's problem.

### PR DESCRIPTION
**Pull request by Jorgee97**
Renamed file to match contribution rules.

### CODE REVIEW

**Comment by AdarshRise** [comment]
Put the problem name in the file as well.

**Comment by Jorgee97** [comment]
Hey @AdarshRise I hope you are doing good. I just want to say that the other files inside the solution folders doesn't contain the name of the problem in it. Just the github's username. Also there is not information on the GuideLines for this. 
Quote:

For example if you are solving Problem no 1 in java- >
Your solution should be at -> Java/01.Multiples_of_3_and_5/your_user_name.java

notice: your_user_name.java.

**Comment by AdarshRise** [comment]
I am doing good, True earlier we didn't ask the contributers to put problem statement within the code as a comment, we have changed to such format in order to promote good coding practice and repo integrity, by doing so you help us to evaluate the P.R quickly hence we could maintain the response time at an adequate level.

We have requested the contributers to update their already accepted PR, you may read the same in the thanks note in tha readme.me. 

The quotation you have cited is essential for PR, otherwise it will be marked as invalid( evaluation takes low priority over other PRs). If file name(as per quote) is correct, we ask the contributers to do the needful(if needed), and ask them to go through the guidelines, along with that we evaluate it and tell you If everything is correct or not.

It's just to save time and maintain the quality of Repo.
Happy coding:smile:

**Comment by AdarshRise** [comment]
The new guidelines basically ask you to send a PR with problem statement along with the language(C,CPP,Java etc) mentioned,  and the file(code) should have the problem statement within it.
You may go through the recently merged PRs.

**Comment by Jorgee97** [comment]
I'm sorry for the misunderstanding @AdarshRise, I changed the file to meet the GuideLines. Thanks for your time.

**Comment by AdarshRise** [comment]
All Good.

**Comment by AdarshRise** [comment]
Just make sure Your future PR should have this format " Problemno. done in this_lang "

**Pull request merged**
