### PR TITLE
Created 10. Summation of primes

### PR DESCRIPTION
**Pull request by aravp-mobile**
Added problem 10

### CODE REVIEW

**Comment by imabhishekkumar** [comment]
Hey, thank you for your contribution! Please check the new contribution guideline and modify your PR accordingly. Thanks!

**Comment by aravp-mobile** [comment]
How to do add check mark in the table?

**Comment by imabhishekkumar** [comment]
Hi, for reference check [this](https://github.com/RisingLight/Project-Euler/commit/f5de73ef15f9ff4520782c4e9e5e9190b57a660e)

**Comment by AdarshRise** [comment]
Check guidelines please.

**Pull request closed without merging**
