### PR TITLE
Added Sum Squared Diff for Java #6

### PR DESCRIPTION
**Pull request by Targgus**

### CODE REVIEW

**Comment by imabhishekkumar** [comment]
Hey, thank you for your contribution! Please check the new contribution guideline and modify your PR accordingly. Thanks!

**Comment by Targgus** [comment]
Sorry for the multiple commits there. Still learning!

**Comment by AdarshRise** [comment]
Code has fault, make needful changes to PR, and resolve conflict.{ do a git pull }

**Comment by AdarshRise** [comment]
No main?

**Pull request closed without merging**
