### PR TITLE
"Added new python scripts (04. Largest palindrome product)"

### PR DESCRIPTION
**Pull request by amannirala13**
Added solution for 04 in python. Time complexity provided (164.999 ms)

### CODE REVIEW

**Comment by AdarshRise** [comment]
Your Result of Question 4 is correct, but the result for  Problem 5 isn't, as you are sending a combined PR{ Both 4 and 5 }, I would ask you to re-evaluate Problem 5.

**Comment by amannirala13** [comment]
> 
> 
> Your Result of Question 4 is correct, but the result for Problem 5 isn't, as you are sending a combined PR{ Both 4 and 5 }, I would ask you to re-evaluate Problem 5.

Hi, the output of the script for the question 5 is verified using the project euler website. If the list is looking confusing I would like to tell you that I remover all the factors of the numbers included in the list to reduce time complexity. Check the 'check' list and you would understand as '20' is included '2', '5', '4' need not be included. Any number divided by the '20' will be divided by all of the numbers.

**Comment by amannirala13** [comment]
Check the output:
image

**Comment by imabhishekkumar** [comment]
@amannirala13 I have checked in project euler website, the answer from your python script (q5) isn't giving the correct output.

**Comment by amannirala13** [comment]
> 
> 
> @amannirala13 I have checked in project euler website, the answer from your python script (q5) isn't giving the correct output.

Oh, I see. I guess I missed something in the creation of the check list. Did a quick fix! It should return the correct output now. The bug might have been created when I was trying to optimize the brute force algorithm

**Pull request merged**
