### PR TITLE
Problem 50 in C

### PR DESCRIPTION
**Pull request by ValentinDSJ**
Problem 50 (Consecutive sum of primes) done in C.

### CODE REVIEW

**Comment by ValentinDSJ** [comment]
Ready for reviewing.
Thank you for your time.

**Comment by AdarshRise** [comment]
Resolve conflict. Do a Git pull first.

**Comment by ValentinDSJ** [comment]
That's weird, I don't think I had a conflict earlier.
Sorry for that.

**Comment by AdarshRise** [comment]
All good.

**Pull request merged**
