### PR TITLE
Solutions in Python [20 28 29 30 50] and  R [1]

### PR DESCRIPTION
**Pull request by said3427**
Some solutions.

### CODE REVIEW

**Comment by AdarshRise** [comment]
Put Problem in file as well.

**Comment by said3427** [comment]
I have added the Problem number and statement as comment 😄

**Comment by AdarshRise** [comment]
There is a read me conflict, Just Resolve that, And This P.R will be ready for merge. =)

**Comment by AdarshRise** [comment]
Resolve The Conflict, do a git Pull.

**Comment by said3427** [comment]
Done

**Comment by AdarshRise** [comment]
Well done. Merged.

**Pull request merged**
