### PR TITLE
25 done in Python

### PR DESCRIPTION
**Pull request by RodolfoFerro**

### CODE REVIEW

**Comment by imabhishekkumar** [comment]
Hey, thank you for your contribution! Please check the new contribution guideline and modify your PR accordingly. Thanks!

**Comment by RodolfoFerro** [comment]
Hey @imabhishekkumar, I've updated accordingly. :)

**Comment by AdarshRise** [comment]
Put problem in file as well.

**Comment by RodolfoFerro** [comment]
Okay, I think I'm done.

**Comment by AdarshRise** [comment]
Well done,  you may need to do a git pull first to reslove this conflict. Happy coding :smile:

**Comment by RodolfoFerro** [comment]
There you go. 😉

**Comment by AdarshRise** [comment]
Good to go.

**Pull request merged**
