### PR TITLE
1 done in C#

### PR DESCRIPTION
**Pull request by arya-prof**

### CODE REVIEW

**Review by Prhmma — APPROVED** [review]

**Comment by AdarshRise** [comment]
Put Problem no. in file { as comment}.

**Comment by AdarshRise** [comment]
I added the readme edit for you, just put problem no. in file, and do a git pull before that.

**Comment by arya-prof** [comment]
done

**Comment by AdarshRise** [comment]
do a git pull to resolve conflict.

**Comment by AdarshRise** [comment]
Resolved for you.

**Pull request merged**
