### PR TITLE
problem 7 10001st prime solved

### PR DESCRIPTION
**Pull request by akarshsingh9**
Problem solved in Dart

### CODE REVIEW

**Comment by imabhishekkumar** [comment]
Hi, your PR is using the uneven version of this repository. Please update the repository that you've forked, make changes and submit PR. We'll be happy to merge then!

**Comment by imabhishekkumar** [comment]
Also, see the contribution guidelines.

**Comment by akarshsingh9** [comment]
file renamed

**Comment by akarshsingh9** [comment]
files renamed

**Pull request merged**
