### PR TITLE
Adding python script for 02 Even Fibonacci numbers

### PR DESCRIPTION
**Pull request by amannirala13**

### CODE REVIEW

**Comment by amannirala13** [comment]
Added the solution for 02 Even Fibonacci numbers in Python

**Comment by AdarshRise** [comment]
Result for Fibonacci number, is not correct, a small bug is there. I would encourage you to find it out.

**Comment by amannirala13** [comment]
> 
> 
> Result for Fibonacci number, is not correct, a small bug is there. I would encourage you to find it out.

Well, thanks for the  reply but the answer generated by the script and the answer accepted by the Euler website were exactly same.

Please check this image for reference:
image

**Comment by amannirala13** [comment]
> 
> 
> Result for Fibonacci number, is not correct, a small bug is there. I would encourage you to find it out.

Okay, I guess I forgot to add a last minute change that I made to the commit. The range was defined 101 for testing, then I changed it to 4 million. Created a new PR with the solution.

**Pull request closed without merging**
